language: cpp
cache: ccache
sudo: false
dist: xenial
os:
  - linux
git:
  depth: 10
  submodules: true

env:
  global:
    - CCACHE_SLOPPINESS=pch_defines,time_macros

matrix:
  include:
    - os: linux
      env: 
        - C_COMPILER=gcc-7
        - CXX_COMPILER=g++-7
        - BUILD_CONFIGURATION=Release
      addons: &gcc7_amd64
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-7
            - libgles2-mesa-dev
            - libegl1-mesa-dev
            - libfreeimage-dev
            - libcrypto++-dev
            - liblockfile-dev
            - liblua5.1-0-dev
            - libncurses5-dev
            - libpugixml-dev
            - libopenal-dev
            - libtheora-dev
            - libvorbis-dev
            - libglew-dev
            - liblzo2-dev
            - libjpeg-dev
            - libsdl2-dev
            - libtbb-dev
            - libssl-dev
            - libogg-dev
            - ninja-build

    - os: linux
      env: 
        - C_COMPILER=gcc-7
        - CXX_COMPILER=g++-7
        - BUILD_CONFIGURATION=Debug
      addons: *gcc7_amd64

    - os: linux
      env: 
        - C_COMPILER=gcc-7
        - CXX_COMPILER=g++-7
        - CFLAGS="-m32 -msse -msse2"
        - CXXFLAGS="-m32 -msse -msse2"
        - ASMFLAGS="-m32"
        - BUILD_CONFIGURATION=Release
      addons: &gcc7_i386
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-7
            - libgles2-mesa-dev:i386
            - libegl1-mesa-dev:i386
            - libfreeimage-dev:i386
            - libcrypto++-dev:i386
            - liblockfile-dev:i386
            - liblua5.1-0-dev:i386
            - libncurses5-dev:i386
            - libglib2.0-dev:i386
            - libpugixml-dev:i386
            - libopenal-dev:i386
            - libtheora-dev:i386
            - libvorbis-dev:i386
            - libpulse-dev:i386
            - libglew-dev:i386
            - liblzo2-dev:i386
            - libjpeg-dev:i386
            - libsdl2-dev:i386
            - libtbb-dev:i386
            - libssl-dev:i386
            - libogg-dev:i386
            - gcc-multilib
            - g++-7-multilib
            - ninja-build

    - os: linux
      env: 
        - C_COMPILER=gcc-7
        - CXX_COMPILER=g++-7
        - CFLAGS="-m32 -msse -msse2"
        - CXXFLAGS="-m32 -msse -msse2"
        - ASMFLAGS="-m32"
        - BUILD_CONFIGURATION=Debug
      addons: *gcc7_i386

before_script:
  - export CC=$C_COMPILER
  - export CXX=$CXX_COMPILER
  - ccache --show-stats
  - mkdir bin
  - cd bin
  - cmake .. -GNinja -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION

script:
  - export core_count=$(nproc || echo 2) && echo core_count = $core_count
  - cmake --build . -j $core_count

after_script:
  - ccache --show-stats

notifications:
  email: false
